### ISSUE TITLE
[Issue - Minor] CoalGrinder drops wrong block when broken

### ISSUE THREAD

**Issue by accessdenied0** [Rumaruka/SimpleGrinder#10]
Hey @Rumaruka,

I just want to point out that in the version 1.244.A194 if you break a CoalGrinder you get a Furnace back. Not sure if this is supposed to be, but is there a way (except Silk-touch) to keep the Grinder?

access_denied

**Comment by Rumaruka** [comment]
Fixed
Grab in Curse @accessdenied0

**Comment by accessdenied0** [comment]
@Rumaruka,

Yeah thank you a lot! It is fixed! I'll close it.
