### ISSUE TITLE
Ore Dictionary required!

### ISSUE THREAD

**Issue by MJRamon** [Rumaruka/SimpleGrinder#12]
Simple Grinder doesn't know about any modded ore, as I can see. For example, there is Base Metals mod (adds basic ores, dusts etc, like copper, tin, lead and so on). We need ore dictionary support, thanks!

**Comment by Rumaruka** [comment]
I trying :)

**Comment by jriwanek** [comment]
@Rumaruka If you need help just let me know.

**Comment by Rumaruka** [comment]
@jriwanek thank you :)

**Comment by Rumaruka** [comment]
Ore Dict Enable in 1.12.2 version MC
