### ISSUE TITLE
SHIFT+clicking causes crash, normal placement is fine

### ISSUE THREAD

**Issue by AndaleTheGreat** [Rumaruka/SimpleGrinder#21]
Had a crash report, but got distracted and lost the paste of it, will get you another when I get a few minutes. These are all the mods I am using + versions: http://i.imgur.com/kcETHbX.png

SimpleGrinder 3.025.R111
Forge 13.19.0.2178

**Comment by Rumaruka** [comment]
I know,  Don't use "shift click", drag ONE fuels 
I try fix this crash

**Comment by AndaleTheGreat** [comment]
Hoppers work fine as well at least. :)

**Comment by Rumaruka** [comment]
Fix
Close #21
