### ISSUE TITLE
[Request] Support for Botania and the Exoflame flower

### ISSUE THREAD

**Issue by Hund** [Rumaruka/SimpleGrinder#27]
The Exoflame flower from Botania is a flower that fuels furnaces with mana. And the more flowers you have, the faster the furnace is.

It would be really cool if this mod would support it. :)

**Comment by Rumaruka** [comment]
Separate mode only

**Comment by Hund** [comment]
Hm?

**Comment by Rumaruka** [comment]
Make addon for Botania, add crusher and more stuff, maybe
