### ISSUE TITLE
[1.12] Poof! crash...

### ISSUE THREAD

**Issue by Migmag789** [Rumaruka/SimpleGrinder#28]
Hey Rumaruka ! There is a crash with your mod in Beyond the Minecraft, i'm trying to updating this...
I use 2387 version of forge ;)
[crash-2017-06-29_17.29.50-client.txt](https://github.com/Rumaruka/SimpleGrinder/files/1112593/crash-2017-06-29_17.29.50-client.txt)

**Comment by Rumaruka** [comment]
Update my mod 4.050.R112

**Comment by Rumaruka** [comment]
Delete and Setup Again
