### ISSUE TITLE
CraftTweaker Support Question

### ISSUE THREAD

**Issue by orionSquared** [Rumaruka/SimpleGrinder#29]
Good evening! I hate to ask a stupid question, but is your mod compatible with crafttweaker? And if so, what sort of code can I use to implement a grinder recipe?

Your mod is amazing and is exactly what I needed for my modpack. So I was super happy I found it. Thanks for the good work. :)

**Comment by Rumaruka** [comment]
Mod haven't support with Crafttweaker,  I think,  I see api and make :)

**Comment by Rumaruka** [comment]
API Crafttweaker I don't understand
Maybe Im never add support :(

Close and sorry :(
