### ISSUE TITLE
Bone duplication issue

### ISSUE THREAD

**Issue by jonqrandom** [Rumaruka/SimpleGrinder#31]
With its default settings, this mod allows duping of bones and related items; one bone block grinds into 6 bones, which grind into 30 bonemeal, which crafts 3 bone blocks and 3 bonemeal to spare. A 2nd cycle yields 10 blocks and 3 bonemeal, and so on!

**Comment by Rumaruka** [comment]
You want me to nerf ? :D

**Comment by jonqrandom** [comment]
hey, it's your mod, just thought i should mention it lol ;p
