### ISSUE TITLE
Simple grinder completely ignores the output in the config

### ISSUE THREAD

**Issue by Insane-96** [Rumaruka/SimpleGrinder#34]
I have the following config file and even if the output is set to 0 the recipes are not removed. I can still grind everything

```
general {
    # Output Amount
    I:BoneMealOutput=0

    # Output Amount
    I:BoneOutput=0

    # Output Amount
    I:BookOutput=0

    # Output Amount
    I:BrickOutput=0

    # Output Amount
    I:CactusGreenOutput=0

    # Output Amount
    I:CoalOutput=0

    # Output Amount
    I:CobbleSandOutput=0

    # Output Amount
    I:DiamondHorseArmorOutput=0

    # Output Amount
    I:DiamondOutput=0

    # Output Amount
    I:EmeraldOutput=0

    # Output Amount
    I:FlintOutput=0

    # Output Amount
    I:FlourOutput=0

    # Output Amount
    I:GoldDustHorseArmorOutput=0

    # Output Amount
    I:GoldDustOutput=2

    # Output Amount
    I:IronDustHorseArmorOutput=0

    # Output Amount
    I:IronDustOutput=2

    # Output Amount
    I:LapisOutput=0

    # Output Amount
    I:MashedCarrotOutput=0

    # Output Amount
    I:MashedPotatoOutput=0

    # Output Amount
    I:OmleteOutput=0

    # Output Amount
    I:PrisMarineshardOutput=0

    # Output Amount
    I:QuartzOutput=4

    # Output Amount
    I:RedStoneOutput=0

    # Output Amount
    I:SandstoneSandOutput=0

    # Output Amount
    I:WoodChipsOutput=0
    S:blacklistDusts <
        dustCoal
     >
}
```

**Comment by Rumaruka** [comment]
Hmm strange, Im looking
Thanks

**Comment by Rumaruka** [comment]
So,  I looking all version and change different amounts,  you right - if change 0 config don't work,  but if you choose numeric 1 and other: config work. 
I think,  config don't like number 0 ;) 
In future I'm found way "how delete crusher recipe" 

Close #34

**Comment by Insane-96** [comment]
Seems like that works for some things like mashed carrots, flour, and things added by the mod.

I think a good way to fix this would be to remove completely the "general" category and move all the recipes from "general" to "recipe" so it no longer gives problems.

So instead of having
```
 # Output Amount
    I:BoneMealOutput=4
```
You will have
`{"inputItem":"bone","outputItem":"dye/15#4","experience":0.1}`

**Comment by Rumaruka** [comment]
Hmm, It`s greate idea, Im make this in major update :D
