### ISSUE TITLE
coal grinder wont process more than one ore

### ISSUE THREAD

**Issue by mcsper** [Rumaruka/SimpleGrinder#35]
if i have a stack of ore in the grinder it will process the first ore then do nothing and run out of fuel unless i take the ore out and put it back in again

**Comment by Rumaruka** [comment]
So far, I have no idea how to fix this bug, I used code from the Furnus mod, and probably there is the same bug. It's very strange why this happens. I'll fix it in the next time!

**Comment by Rumaruka** [comment]
Fixed (maybe) un new build
Checked
