### ISSUE TITLE
Latest version (1.143) seems to be empty

### ISSUE THREAD

**Issue by Insane-96** [Rumaruka/SimpleGrinder#36]
There are no blocks, no config, nothing

**Comment by Rumaruka** [comment]
Really?
Can you share screenshot, please

**Comment by Rumaruka** [comment]
I see, i fix

**Comment by Rumaruka** [comment]
Yep Im fix, my mistake 
Sorry
Close

**Comment by Insane-96** [comment]
Nice thanks.

**Comment by Rumaruka** [comment]
http://prntscr.com/ishy4s
Wait
