### ISSUE TITLE
[Suggestion] Change the Grinder GUI to not be like the furnace

### ISSUE THREAD

**Issue by Insane96** [Rumaruka/SimpleGrinder#38]
Because you're actually not cooking the item, but using the fuel to power the grinder

Something like this:
![senza nome](https://user-images.githubusercontent.com/7185104/37588571-db0e40f4-2b62-11e8-8bc8-b355b8887d84.png)

**Comment by Rumaruka** [comment]
Im think about this

**Comment by Kippy232** [comment]
This seems like a great idea! The change in GUI and block texture makes for more a more unique block. It's also a rather quick alteration, as well, all things considered.

**Comment by Davoleo** [comment]
The idea is not bad, I don't really like how the slots are placed though
