### ISSUE TITLE
A broken ore dictionary registration with name dustIron has occurred

### ISSUE THREAD

**Issue by jokish63** [Rumaruka/SimpleGrinder#4]
A broken ore dictionary registration with name dustIron has occurred. It adds an item (type: class com.rumaruka.simplegrinder.Common.items.ItemDustIron) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Simple Grinder report it to them!

Gold has the same Problem.

log: http://paste.ee/p/ubZFZ

**Comment by Rumaruka** [comment]
Fix in new version,  thank you for report!

**Comment by Rumaruka** [comment]
Fixed,  thank you for report. 
If you found new error tell about this;)
