### ISSUE TITLE
[1.14] Recipe doesn't work in 1.14 Fabric

### ISSUE THREAD

**Issue by Boomflex** [Rumaruka/SimpleGrinder#41]
![image](https://user-images.githubusercontent.com/22868795/50303604-7fa21180-0485-11e9-8f4c-9a4fd35d082d.png)

**Comment by Rumaruka** [comment]
I know, I don`t make recipes for Coal Grinder, because Coal Grinder don`t worked D:

**Comment by Knito58** [comment]
Came here to report said error and now found it already known. But - the main block of the mod is broken and you'll fix it "**in future**"????? You're the only one providing such grinder mod for 1.14 snap at this moment so you may be lucky and people might not already have turned their back to this mod when the fix finally will be provided.

**Comment by Rumaruka** [comment]
Ty, but i don`t work SG for Fabric D:

**Comment by Knito58** [comment]
Sigh. :/

**Comment by Rumaruka** [comment]
I think , I don`t update mod for fabric D: Waiting Forge
