### ISSUE TITLE
Crash on 1.14 19w11b

### ISSUE THREAD

**Issue by The-Fireplace** [Rumaruka/SimpleGrinder#42]
This crash occurs when starting the game:
https://paste.ubuntu.com/p/swKgqf8Vmt/
I removed all mods then re-added one by one until the crash occurred again, and found that Simple Grinder was the cause.
fabric-loader-0.3.7.109-19w11b.2
SimpleGrinder 1.0.0

**Comment by Rumaruka** [comment]
I don't update new version fabric :(

**Comment by Rumaruka** [comment]
I think , I don`t update mod for fabric D: Waiting Forge
