### ISSUE TITLE
Disabling Built In Dust Recipes does nothing

### ISSUE THREAD

**Issue by Boolyman** [Rumaruka/SimpleGrinder#48]
I have toggled the option in the config to not load the built in dust recipes, because I don't want players being able to TRIPLE their ores 10 minutes into the modpack.  But the ore to dust recipes are still showing.  Anyway you can fix this?  That seems like a very overpowered setting to have as default in your mod.

**Comment by Boolyman** [comment]
Hello?

**Comment by Rumaruka** [comment]
Sorry, but I don't work SG for now

**Comment by Knito58** [comment]
simplegrinder-16.0.4 on 1.16.1 Forge 32.0.38

Loved ore-tripling because I am on a poor island. Didn't find any config file to make it triple again as it is set to double ores since this version.
