### ISSUE TITLE
[1.14.4] Coal Grinder Not Working

### ISSUE THREAD

**Issue by coolsimulations** [Rumaruka/SimpleGrinder#49]
Using `SimpleGrinder-1.14.4-a0.1` with Forge `1.14.4-28.1.20` and when placing a Coal Grinder and rick-clicking on it, it does nothing. It does not open the GUI and thus I cannot use it to turn ores into dusts.

Steps To Reproduce:
1. Place Coal Grinder
2. Right Click on it
3. Nothing happens

Heres the debug log if that helps:
[debug.log](https://github.com/Rumaruka/SimpleGrinder/files/3664873/debug.log)

**Comment by Rumaruka** [comment]
I know

**Comment by Rumaruka** [comment]
Read changelog
