### ISSUE TITLE
simplegrinder mod not loading

### ISSUE THREAD

**Issue by DuhItzBear** [Rumaruka/SimpleGrinder#50]
I installed this mod via curseforge, I'm running 1.14.4 and evertime at setup no matter how many mods I leave out or how many times I reinstall it leaves the same message: 
"Simple Grinder (simplegrinder) encountered an error during the sided_setup event phase
Duplicate registration for null"
No, I'm not really good at informatics, but homegirl struggling.
I have a lot of other mods but as I said even if I remove them its still the same, any suggestions to make it work?

**Comment by Rumaruka** [comment]
I don`t develop mods for 1.12.2 for this moment. Mb later :(

**Comment by DuhItzBear** [comment]
Oh ok that might be the source of the problem then, Tank you!
