### ISSUE TITLE
Help needed finding config file

### ISSUE THREAD

**Issue by Knito58** [Rumaruka/SimpleGrinder#53]
simplegrinder-16.0.4 on 1.16.1 Forge 32.0.38

Loved ore-tripling because I am on a poor island. Didn't find any config file to make it triple again as it is set to double ores since this version.

**Comment by Rumaruka** [comment]
1 ore -> 3 dust always , can you show with screenshot me about this problem?

**Comment by Knito58** [comment]
Sorry, it still is "2" after restarting the game.
Copying the screenshot tells me that "something went really wrong...". Ok, I have a dropbox link here:

![Image of GUI](https://www.dropbox.com/s/0hc11wusizroqvz/gui.jpg?dl=0)

https://www.dropbox.com/s/0hc11wusizroqvz/gui.jpg?dl=0

**Comment by Rumaruka** [comment]
Strange , I'm checked later

**Comment by Rumaruka** [comment]
Forge 32.0.38 broken 
![image](https://user-images.githubusercontent.com/8148679/86242002-5eaf9600-bbbd-11ea-9c6c-205646924572.png)

**Comment by Rumaruka** [comment]
Forge 32.0.38 broken - wait new version

**Comment by Rumaruka** [comment]
fix 32.0.38, but ALL worked
![image](https://user-images.githubusercontent.com/8148679/86251094-dd5f0000-bbca-11ea-9fa4-3136773a7831.png)

**Comment by Knito58** [comment]
This looked very good. Something I'd like to see in my GUI, too. As you reopened the issue, there still seem to be some problems.
Take your time.

**Comment by Knito58** [comment]
I have version SG 16.0.5 now. The GUI still saying "2" dust as a result. But counting the items given back - this is tripled. So it works. I consider this as "fixed" and will close that issue.
