### ISSUE TITLE
FIX for 1.16.3 - change 'versionRange="[1.16.3]"' in mods.toml

### ISSUE THREAD

**Issue by markygnlg** [Rumaruka/SimpleGrinder#54]
I saw you post [[Posted Sep 27, 2020 #166](https://www.curseforge.com/minecraft/mc-mods/simple-grinder?comment=166)]

Quote from Rumaruka >>
In reply to juliawastaaken:

 Yes, Im update mod for this version, but I have little time for it=(

Just thought I'd let you know that if you change 'versionRange=' in mods.toml from '1.16.2' to 1.16.3' it will make this work for v1.16.3

**Comment by Rumaruka** [comment]
don`t work this solution
Im make this version later
