### ISSUE TITLE
Names [1.16.5]

### ISSUE THREAD

**Issue by vertex101** [Rumaruka/SimpleGrinder#56]
the names of the core and coal grinder are not showing right 

https://i.imgur.com/eP1KhhO.png

**Comment by Rumaruka** [comment]
My project after reinstall windows deleted! 
I rewrite mod for 1.16.5 and 1.17, but I'm an official worker and I don`t have time for this

**Comment by vertex101** [comment]
Well when I get home from work I will look at the code then will send a pull request for the fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
