### ISSUE TITLE
The grinder insta breaks (tried with netherite, so I could be wrong there) and doesn't drop any items from its inventory 

### ISSUE THREAD

**Issue by Nathan22211** [Rumaruka/SimpleGrinder#58]
Someone in the curse comments also reported that the grinder deletes items in it on world reload. Haven't tested that

**Comment by Rumaruka** [comment]
Version mod?

**Comment by Nathan22211** [comment]
18_1.0.1 fabric. I was trying to use it as a dependency in my mod.
