### ISSUE TITLE
Grinder Has No Collision And Deletes Contents When Unloaded

### ISSUE THREAD

**Issue by SophieScott12** [Rumaruka/SimpleGrinder#59]
In version 1.19.2. Exactly what the title says:  the grinder block has no collision.  You can't stand on it and it doesn't stop you, you just walk through.  Furthermore, when the chunk unloads anything inside the grinder is deleted.  This is a massive issue and needs to be fixed.

**Comment by Rumaruka** [comment]
Fixed
Try new version

**Comment by SophieScott12** [comment]
> Fixed Try new version

If you mean the most recent version on curseforge, that's what I have installed.  simplegrinder-1.0.jar for Forge 1.19.2.  If there's another more recent version I don't know of it.

**Comment by Rumaruka** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-grinder/files/4058995
